BIN=bin

CC=avr-gcc
OBJCOPY=avr-objcopy

CFLAGS= -x c -funsigned-char -funsigned-bitfields -O0 -mmcu=attiny1606 -Wall -fpack-struct -fshort-enums -g2 -fdata-sections -ffunction-sections -c -std=gnu99 -MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"

C_OBJS :=
C_SRS :=

# Compiler section


